### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by codedust**

### CODE REVIEW

**Comment by flokli** [comment]
The favicon needs to be in 16x16, yours is 256x256.

**Comment by codedust** [comment]
16x16 is quite small. I used 32x32 instead (according to https://www.w3.org/2005/10/howto-favicon).

**Comment by flokli** [comment]
Hmm… This looks like scaled from the 256x256 png image. Can you use the svg version and render one from that? I'm also missing the svg version inside the https://github.com/freifunk-darmstadt/pr repo…

**Comment by codedust** [comment]
Done. I also added the svg version in the pr repo.

**Comment by flokli** [comment]
Thanks! Could you also add apple-touch-icon-precomposed?

```
<link rel="apple-touch-icon-precomposed" sizes="256x256" href="…">
```

**Comment by codedust** [comment]
Is there really anyone who would need this? / Why not add
```html
<link rel="ms-universal-icon-ie9-only" sizes="132x157" href="…">
```
too? Imho, there is no need for propriatary apple html extensions...

**Pull request merged**
